import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "./components/Navber";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "জীবনদীপ্ত রমাদান",
    template: "%s - জীবনদীপ্ত রমাদান",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Navber></Navber>
        <main className="h-screen h-max-[500px]"> 
          {children}
        </main>
       
        {/* <footer className="mt-20 border-t border-gray-200 py-6 text-center text-sm text-gray-600">
      <p>
        © {new Date().getFullYear()} — Crafted with care by{' '}
        <span className="font-semibold text-gray-200">
          Sadat Hassan Labib
        </span>
      </p>

      <p className="mt-1 text-xs text-gray-200">
        All rights reserved.
      </p>
    </footer> */}
      </body>
    </html>
  );
}
